<?php

namespace Amz\ListingsItems;

use OpenAPI\Runtime\ResponseTypes as AbstractResponseTypes;

class ResponseTypes extends AbstractResponseTypes
{
    public static $types = [
        'getItemEligibilityPreview' => [
            '200.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '400.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '401.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '403.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '404.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '429.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '500.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '503.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
        ],
        'listFinancialEventGroups' => [
            '200.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '400.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '403.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '404.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '429.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '500.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '503.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
        ],
        'listFinancialEventsByGroupId' => [
            '200.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '400.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '403.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '404.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '429.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '500.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '503.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
        ],
        'listFinancialEventsByOrderId' => [
            '200.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '400.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '403.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '404.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '429.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '500.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '503.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
        ],
        'listFinancialEvents' => [
            '200.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '400.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '403.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '404.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '429.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '500.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '503.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
        ],
        'getOrders' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\GetOrdersResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
        ],
        'getOrder' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '401.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\GetOrderResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\GetOrderResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrderResponse',
        ],
        'submitAcknowledgement' => [
            '202.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\SubmitAcknowledgementResponse',
            '400.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\SubmitAcknowledgementResponse',
            '403.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\SubmitAcknowledgementResponse',
            '404.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\SubmitAcknowledgementResponse',
            '413.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\SubmitAcknowledgementResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\SubmitAcknowledgementResponse',
            '429.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\SubmitAcknowledgementResponse',
            '500.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\SubmitAcknowledgementResponse',
            '503.' => 'Amz\\VendorDirectFulfillmentOrders\\Model\\SubmitAcknowledgementResponse',
        ],
        'getShipmentDetails' => [
            '200.' => 'Amz\\ShipmentInvoicing\\Model\\GetShipmentDetailsResponse',
            '400.' => 'Amz\\ShipmentInvoicing\\Model\\GetShipmentDetailsResponse',
            '401.' => 'Amz\\ShipmentInvoicing\\Model\\GetShipmentDetailsResponse',
            '403.' => 'Amz\\ShipmentInvoicing\\Model\\GetShipmentDetailsResponse',
            '404.' => 'Amz\\ShipmentInvoicing\\Model\\GetShipmentDetailsResponse',
            '415.' => 'Amz\\ShipmentInvoicing\\Model\\GetShipmentDetailsResponse',
            '429.' => 'Amz\\ShipmentInvoicing\\Model\\GetShipmentDetailsResponse',
            '500.' => 'Amz\\ShipmentInvoicing\\Model\\GetShipmentDetailsResponse',
            '503.' => 'Amz\\ShipmentInvoicing\\Model\\GetShipmentDetailsResponse',
        ],
        'submitInvoice' => [
            '200.' => 'Amz\\ShipmentInvoicing\\Model\\SubmitInvoiceResponse',
            '400.' => 'Amz\\ShipmentInvoicing\\Model\\SubmitInvoiceResponse',
            '401.' => 'Amz\\ShipmentInvoicing\\Model\\SubmitInvoiceResponse',
            '403.' => 'Amz\\ShipmentInvoicing\\Model\\SubmitInvoiceResponse',
            '404.' => 'Amz\\ShipmentInvoicing\\Model\\SubmitInvoiceResponse',
            '415.' => 'Amz\\ShipmentInvoicing\\Model\\SubmitInvoiceResponse',
            '429.' => 'Amz\\ShipmentInvoicing\\Model\\SubmitInvoiceResponse',
            '500.' => 'Amz\\ShipmentInvoicing\\Model\\SubmitInvoiceResponse',
            '503.' => 'Amz\\ShipmentInvoicing\\Model\\SubmitInvoiceResponse',
        ],
        'getInvoiceStatus' => [
            '200.' => 'Amz\\ShipmentInvoicing\\Model\\GetInvoiceStatusResponse',
            '400.' => 'Amz\\ShipmentInvoicing\\Model\\GetInvoiceStatusResponse',
            '401.' => 'Amz\\ShipmentInvoicing\\Model\\GetInvoiceStatusResponse',
            '403.' => 'Amz\\ShipmentInvoicing\\Model\\GetInvoiceStatusResponse',
            '404.' => 'Amz\\ShipmentInvoicing\\Model\\GetInvoiceStatusResponse',
            '415.' => 'Amz\\ShipmentInvoicing\\Model\\GetInvoiceStatusResponse',
            '429.' => 'Amz\\ShipmentInvoicing\\Model\\GetInvoiceStatusResponse',
            '500.' => 'Amz\\ShipmentInvoicing\\Model\\GetInvoiceStatusResponse',
            '503.' => 'Amz\\ShipmentInvoicing\\Model\\GetInvoiceStatusResponse',
        ],
        'SubmitShipmentConfirmations' => [
            '202.' => 'Amz\\VendorShipments\\Model\\SubmitShipmentConfirmationsResponse',
            '400.' => 'Amz\\VendorShipments\\Model\\SubmitShipmentConfirmationsResponse',
            '403.' => 'Amz\\VendorShipments\\Model\\SubmitShipmentConfirmationsResponse',
            '404.' => 'Amz\\VendorShipments\\Model\\SubmitShipmentConfirmationsResponse',
            '413.' => 'Amz\\VendorShipments\\Model\\SubmitShipmentConfirmationsResponse',
            '415.' => 'Amz\\VendorShipments\\Model\\SubmitShipmentConfirmationsResponse',
            '429.' => 'Amz\\VendorShipments\\Model\\SubmitShipmentConfirmationsResponse',
            '500.' => 'Amz\\VendorShipments\\Model\\SubmitShipmentConfirmationsResponse',
            '503.' => 'Amz\\VendorShipments\\Model\\SubmitShipmentConfirmationsResponse',
        ],
        'getSmallAndLightEnrollmentBySellerSKU' => [
            '200.' => 'Amz\\FbaSmallAndLight\\Model\\SmallAndLightEnrollment',
            '400.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '403.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '404.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '413.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '415.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '429.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '500.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '503.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
        ],
        'putSmallAndLightEnrollmentBySellerSKU' => [
            '200.' => 'Amz\\FbaSmallAndLight\\Model\\SmallAndLightEnrollment',
            '400.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '403.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '404.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '413.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '415.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '429.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '500.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '503.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
        ],
        'deleteSmallAndLightEnrollmentBySellerSKU' => [
            '400.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '403.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '404.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '413.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '415.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '429.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '500.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '503.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
        ],
        'getSmallAndLightEligibilityBySellerSKU' => [
            '200.' => 'Amz\\FbaSmallAndLight\\Model\\SmallAndLightEligibility',
            '400.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '403.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '404.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '413.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '415.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '429.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '500.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '503.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
        ],
        'getSmallAndLightFeePreview' => [
            '200.' => 'Amz\\FbaSmallAndLight\\Model\\SmallAndLightFeePreviews',
            '400.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '401.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '403.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '404.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '429.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '500.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '503.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
        ],
        'getOrderBuyerInfo' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
        ],
        'getOrderAddress' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
        ],
        'getOrderItems' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
        ],
        'getOrderItemsBuyerInfo' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
        ],
        'getShippingLabels' => [
            '200.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelListResponse',
            '400.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelListResponse',
            '403.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelListResponse',
            '404.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelListResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelListResponse',
            '429.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelListResponse',
            '500.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelListResponse',
            '503.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelListResponse',
        ],
        'submitShippingLabelRequest' => [
            '202.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShippingLabelsResponse',
            '400.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShippingLabelsResponse',
            '403.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShippingLabelsResponse',
            '404.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShippingLabelsResponse',
            '413.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShippingLabelsResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShippingLabelsResponse',
            '429.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShippingLabelsResponse',
            '500.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShippingLabelsResponse',
            '503.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShippingLabelsResponse',
        ],
        'getShippingLabel' => [
            '200.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelResponse',
            '400.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelResponse',
            '401.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelResponse',
            '403.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelResponse',
            '404.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelResponse',
            '429.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelResponse',
            '500.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelResponse',
            '503.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetShippingLabelResponse',
        ],
        'submitShipmentConfirmations' => [
            '202.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentConfirmationsResponse',
            '400.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentConfirmationsResponse',
            '403.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentConfirmationsResponse',
            '404.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentConfirmationsResponse',
            '413.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentConfirmationsResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentConfirmationsResponse',
            '429.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentConfirmationsResponse',
            '500.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentConfirmationsResponse',
            '503.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentConfirmationsResponse',
        ],
        'submitShipmentStatusUpdates' => [
            '202.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentStatusUpdatesResponse',
            '400.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentStatusUpdatesResponse',
            '403.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentStatusUpdatesResponse',
            '404.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentStatusUpdatesResponse',
            '413.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentStatusUpdatesResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentStatusUpdatesResponse',
            '429.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentStatusUpdatesResponse',
            '500.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentStatusUpdatesResponse',
            '503.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\SubmitShipmentStatusUpdatesResponse',
        ],
        'getCustomerInvoices' => [
            '200.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoicesResponse',
            '400.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '403.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '404.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '429.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '500.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '503.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
        ],
        'getCustomerInvoice' => [
            '200.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '400.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '401.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '403.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '404.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '429.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '500.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
            '503.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetCustomerInvoiceResponse',
        ],
        'getPackingSlips' => [
            '200.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipListResponse',
            '400.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipListResponse',
            '401.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipListResponse',
            '403.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipListResponse',
            '404.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipListResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipListResponse',
            '429.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipListResponse',
            '500.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipListResponse',
            '503.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipListResponse',
        ],
        'getPackingSlip' => [
            '200.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipResponse',
            '400.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipResponse',
            '401.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipResponse',
            '403.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipResponse',
            '404.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipResponse',
            '415.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipResponse',
            '429.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipResponse',
            '500.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipResponse',
            '503.' => 'Amz\\VendorDirectFulfillmentShipping\\Model\\GetPackingSlipResponse',
        ],
        'getSubscription' => [
            '200.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '400.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '403.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '404.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '413.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '415.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '429.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '500.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '503.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
        ],
        'createSubscription' => [
            '200.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '400.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '403.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '404.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '409.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '413.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '415.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '429.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '500.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '503.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
        ],
        'getSubscriptionById' => [
            '200.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '400.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '403.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '404.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '409.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '413.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '415.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '429.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '500.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '503.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
        ],
        'deleteSubscriptionById' => [
            '200.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '400.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '403.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '404.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '409.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '413.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '415.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '429.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '500.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '503.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
        ],
        'getDestinations' => [
            '200.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '400.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '403.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '404.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '409.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '413.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '415.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '429.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '500.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '503.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
        ],
        'createDestination' => [
            '200.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '400.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '403.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '404.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '409.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '413.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '415.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '429.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '500.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '503.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
        ],
        'getDestination' => [
            '200.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '400.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '403.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '404.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '409.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '413.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '415.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '429.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '500.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '503.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
        ],
        'deleteDestination' => [
            '200.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '400.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '403.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '404.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '409.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '413.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '415.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '429.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '500.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '503.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
        ],
        'getMessagingActionsForOrder' => [
            '200.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '400.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '403.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '404.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '413.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '415.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '429.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '500.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '503.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
        ],
        'confirmCustomizationDetails' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
        ],
        'createConfirmDeliveryDetails' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
        ],
        'createLegalDisclosure' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
        ],
        'createNegativeFeedbackRemoval' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
        ],
        'createConfirmOrderDetails' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
        ],
        'createConfirmServiceDetails' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
        ],
        'CreateAmazonMotors' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
        ],
        'CreateWarranty' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
        ],
        'GetAttributes' => [
            '200.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '400.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '403.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '404.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '413.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '415.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '429.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '500.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '503.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
        ],
        'createDigitalAccessKey' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
        ],
        'createUnexpectedProblem' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
        ],
        'getInventorySummaries' => [
            '200.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '400.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '403.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '404.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '429.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '500.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '503.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
        ],
        'getFulfillmentPreview' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
        ],
        'listAllFulfillmentOrders' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
        ],
        'createFulfillmentOrder' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
        ],
        'getPackageTrackingDetails' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
        ],
        'listReturnReasonCodes' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
        ],
        'createFulfillmentReturn' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
        ],
        'getFulfillmentOrder' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
        ],
        'updateFulfillmentOrder' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
        ],
        'cancelFulfillmentOrder' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
        ],
        'getFeatures' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
        ],
        'getFeatureInventory' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
        ],
        'getFeatureSKU' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
        ],
        'getMarketplaceParticipations' => [
            '200.' => 'Amz\\Sellers\\Model\\GetMarketplaceParticipationsResponse',
            '400.' => 'Amz\\Sellers\\Model\\GetMarketplaceParticipationsResponse',
            '403.' => 'Amz\\Sellers\\Model\\GetMarketplaceParticipationsResponse',
            '404.' => 'Amz\\Sellers\\Model\\GetMarketplaceParticipationsResponse',
            '413.' => 'Amz\\Sellers\\Model\\GetMarketplaceParticipationsResponse',
            '415.' => 'Amz\\Sellers\\Model\\GetMarketplaceParticipationsResponse',
            '429.' => 'Amz\\Sellers\\Model\\GetMarketplaceParticipationsResponse',
            '500.' => 'Amz\\Sellers\\Model\\GetMarketplaceParticipationsResponse',
            '503.' => 'Amz\\Sellers\\Model\\GetMarketplaceParticipationsResponse',
        ],
        'getAuthorizationCode' => [
            '200.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '400.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '403.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '404.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '413.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '415.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '429.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '500.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '503.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
        ],
        'putListingsItem' => [
            '200.' => 'Amz\\ListingsItems\\Model\\ListingsItemSubmissionResponse',
            '400.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '403.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '413.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '415.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '429.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '500.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '503.' => 'Amz\\ListingsItems\\Model\\ErrorList',
        ],
        'deleteListingsItem' => [
            '200.' => 'Amz\\ListingsItems\\Model\\ListingsItemSubmissionResponse',
            '400.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '403.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '413.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '415.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '429.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '500.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '503.' => 'Amz\\ListingsItems\\Model\\ErrorList',
        ],
        'patchListingsItem' => [
            '200.' => 'Amz\\ListingsItems\\Model\\ListingsItemSubmissionResponse',
            '400.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '403.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '413.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '415.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '429.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '500.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '503.' => 'Amz\\ListingsItems\\Model\\ErrorList',
        ],
    ];
}
